import Head from "next/head";
import React from "react";
import Colors from "../components/Colors";
import { createObject } from "../utils/data";
import dynamic from "next/dynamic";
import { Suspense } from "react";
const DynmColor = dynamic(() => import("../components/Colors"), {
  ssr: false,
});
export default function Home({ res }) {
  const [hasMounted, setHasMounted] = React.useState(false);
  React.useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Tailwind Palette</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<div>Loading...</div>}>
        <DynmColor res={res} />
      </Suspense>

      {/* <Colors res={res} /> */}
    </>
  );
}
export async function getStaticProps() {
  const res = createObject();
  return {
    props: { res },
  };
}
