import Head from "next/head";
import React from "react";
import Colors from "../components/Colors";
import { createObject } from "../utils/data";
// import dynamic from "next/dynamic";
// import { Suspense } from "react";
// const DynmColor = dynamic(() => import("../components/Colors"), {
//   loading: () => <div>Loading...</div>,
//   ssr: false,
// });
import { res } from "../utils/json";
export default function Home() {
  const [hasMounted, setHasMounted] = React.useState(false);
  React.useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Tailwind Palette</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Suspense>
        <DynmColor res={res} />
      </Suspense> */}
      <Colors res={res} />
    </>
  );
}
